# Generated by Django 4.0.5 on 2022-06-05 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='authr',
            new_name='author',
        ),
    ]
